---
- name: set dropbear config
  uci:
    command: set_object
    config: dropbear
    type: dropbear
    index: 0
    values:
      Port: '{{port}}'
      PasswordAuth: '{{password_auth | int}}'
      RootPasswordAuth: '{{root_password_auth | int}}'
  notify:
    - uci commit dropbear
    - reload dropbear

- name: set authorized_keys
  template:
    src: authorized_keys.j2
    dest: /etc/dropbear/authorized_keys
