---
- name: "set dropbear {{item.key}}"
  uci:
    command: set
    config: dropbear
    index: 0
    type: dropbear
    option: "{{item.key}}"
    value: "{{item.value}}"
  notify:
    - uci commit dropbear
    - reload dropbear